AWSTemplateFormatVersion: "2010-09-09"
Description: Plantilla principal para POC
Parameters:
  Env:
    Type: String
    Description: Determina el ambiente de ejecucion
  BucketTemplates:
    Type: String
    Description: Bucket que almacena plantillas de CF
Resources:

  VPC_Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub >-
        https://s3.amazonaws.com/${BucketTemplates}/Infraestructure/VPC_Stack.yaml
      Parameters:
        Env: !Sub >-
          ${Env}