AWSTemplateFormatVersion: "2010-09-09"
Description: Plantilla principal para POC
Parameters:
  Env:
    Type: String
    Description: Determina el ambiente de ejecucion
  BucketTemplates:
    Type: String
    Description: Bucket que almacena plantillas de CF
Resources:

  # Stack VPC 
  VPCstack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub >-
        https://s3.amazonaws.com/${BucketTemplates}/Repository/Infraestructure/EC2/VPC/VPCstack.yaml
      Parameters:
        Env: !Sub >-
          ${Env}

  # Stack EC2 Public Instances
  EC2PublicInstancestack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub >-
        https://s3.amazonaws.com/${BucketTemplates/Repository/Infraestructure/EC2/Instance/InstancePublicstack.yaml
      Parameters:
        Env: !Sub >-
          ${Env}
        SubPublic: !GetAtt [VPCstack, Outputs.PublicSubnet01]
        VPC: !GetAtt [VPCstack, Outputs.VPCid]
    DependsOn:
      - VPCstack
  
  # Stack EC2 Private Instances
  EC2PrivateInstancestack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub >-
        https://s3.amazonaws.com/${BucketTemplates}/Repository/Infraestructure/EC2/Instance/InstancePrivatestack.yaml
      Parameters:
        Env: !Sub >-
          ${Env}
        SubPrivate: !GetAtt [VPCstack, Outputs.PrivateSubnet01]
        VPC: !GetAtt [VPCstack, Outputs.VPCid]
    DependsOn:
      - VPCstack
  
  # Stack RDS Services
  RDS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub >-
        https://s3.amazonaws.com/${BucketTemplates}/Repository/Infraestructure/RDS/RDS.yaml
      Parameters:
        Env: !Sub >-
          ${Env}
        SubPrivate01: !GetAtt [VPCstack, Outputs.PrivateSubnet01]
        SubPrivate02: !GetAtt [VPCstack, Outputs.PrivateSubnet02]
    DependsOn:
      - VPCstack