AWSTemplateFormatVersion: "2010-09-09"
Description: 
Parameters:
  Env:
    Type: String
    Description: Determina el ambiente de ejecucion
Resources:

  Prueba:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub >-
        prueba-${Env}