AWSTemplateFormatVersion: "2010-09-09"
Description: Plantilla principal para POC
Parameters:
  Env:
    Type: String
    Description: Determina el ambiente de ejecucion
Resources:

  Prueba2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub >-
        prueba5-${Env}